const express = require("express");
const app = express();
const PORT = process.env.PORT || 5000;

// ===== YOUR REFERRALS =====
const TG_REF = "https://t.me/hector_trojanbot?start=r-solprofitportal";
const WEB_REF = "https://trojan.com/@Satoshit";

// ===== SIMPLE ANALYTICS =====
let analytics = {
  total_requests: 0,
  routes_served: 0
};

app.use((req, res, next) => {
  analytics.total_requests++;
  next();
});

// ======================================================
// ROOT (API IDENTITY)
// ======================================================
app.get("/", (req, res) => {
  res.json({
    service: "Trojan Execution Gateway API",
    status: "online",
    purpose: "discovery_and_routing",
    data_type: "simulated",
    not_real_market_data: true,
    available_features: [
      "Routing to Trojan for Copy Trading",
      "Routing to Trojan for Token Analysis",
      "Routing to Trojan for Alerts",
      "Routing to Trojan for Execution"
    ],
    disclaimer:
      "This API provides simulated preview data only and never executes trades or provides real market data.",
    analytics
  });
});

// ======================================================
// PUMP.FUN DISCOVERY (SIMULATED PREVIEW)
// ======================================================
app.get("/pumpfun/trending", (req, res) => {
  analytics.routes_served++;

  res.json({
    data_type: "simulated",
    purpose: "discovery_and_routing",
    not_real_market_data: true,

    platform_context: "pump.fun",
    source: "trojan-demo",

    signal_preview: {
      interest: "bullish",
      confidence_score: 0.82,
      description:
        "Example preview to demonstrate how developers can route users to Trojan for real analysis and execution."
    },

    disclaimer:
      "This data is simulated and provided for demonstration and routing purposes only. It is not real market data and must not be used for trading decisions.",

    next_step: {
      action: "use_trojan_for_real_features",
      execute: {
        telegram: {
          label: "Analyze & Trade via Trojan Telegram Bot",
          url: TG_REF
        },
        web: {
          label: "Analyze & Trade via Trojan Web Terminal",
          url: WEB_REF
        }
      }
    }
  });
});

// ======================================================
// COPY TRADING (ROUTING ONLY)
// ======================================================
app.get("/copy-trading/top-wallets", (req, res) => {
  analytics.routes_served++;

  res.json({
    data_type: "simulated",
    purpose: "routing_only",
    feature: "copy_trading_preview",

    description:
      "Preview endpoint to route users to Trojan for real copy trading features.",

    disclaimer:
      "No wallet performance data is provided. All copy trading occurs externally on Trojan.",

    next_step: {
      execute: {
        telegram: TG_REF,
        web: WEB_REF
      }
    }
  });
});

// ======================================================
// TOKEN ANALYSIS (ROUTING ONLY)
// ======================================================
app.get("/token/audit", (req, res) => {
  analytics.routes_served++;

  res.json({
    data_type: "simulated",
    purpose: "routing_only",
    feature: "token_analysis_preview",

    description:
      "Preview endpoint to direct users to Trojan for full token analysis and audits.",

    disclaimer:
      "This endpoint does not perform real audits or contract analysis.",

    next_step: {
      execute: {
        telegram: TG_REF,
        web: WEB_REF
      }
    }
  });
});

// ======================================================
// ALERTS (ROUTING ONLY)
// ======================================================
app.get("/alerts/latest", (req, res) => {
  analytics.routes_served++;

  res.json({
    data_type: "simulated",
    purpose: "routing_only",
    feature: "alerts_preview",

    description:
      "Preview alerts to demonstrate routing users to Trojan for real-time alerts.",

    disclaimer:
      "No real alerts are generated by this API.",

    next_step: {
      execute: {
        telegram: TG_REF,
        web: WEB_REF
      }
    }
  });
});

// ======================================================
// WATCHLISTS (ROUTING ONLY)
// ======================================================
app.get("/watchlists/sample", (req, res) => {
  analytics.routes_served++;

  res.json({
    data_type: "simulated",
    purpose: "routing_only",
    feature: "watchlists_preview",

    description:
      "Sample watchlist preview directing users to Trojan for real watchlist management.",

    next_step: {
      execute: {
        telegram: TG_REF,
        web: WEB_REF
      }
    }
  });
});

// ======================================================
// PNL (ROUTING ONLY)
// ======================================================
app.get("/pnl/card", (req, res) => {
  analytics.routes_served++;

  res.json({
    data_type: "simulated",
    purpose: "routing_only",
    feature: "pnl_preview",

    description:
      "Demonstration PnL preview routing users to Trojan for real performance tracking.",

    disclaimer:
      "No real profit or loss data is calculated by this API.",

    next_step: {
      execute: {
        telegram: TG_REF,
        web: WEB_REF
      }
    }
  });
});

// ======================================================
// ANALYTICS (INTERNAL)
// ======================================================
app.get("/analytics", (req, res) => {
  res.json({
    usage: analytics,
    note: "Internal usage metrics only."
  });
});

app.listen(PORT, () => {
  console.log("Trojan Execution Gateway API running on port " + PORT);
});
